services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mushroom_classification
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Для постоянства данных
      - ./database:/docker-entrypoint-initdb.d  # Указываем путь к скрипту

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - my_network
    restart: unless-stopped

  app:
    build: .
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: mushroom_classification
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      REDIS_HOST: redis  # Подключение к Redis
      REDIS_PORT: 6379
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis  # Убедитесь, что Redis запущен перед приложением
    networks:
      - my_network
    restart: unless-stopped

  celery:
    build: .
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: mushroom_classification
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      REDIS_HOST: redis  # Подключение к Redis
      REDIS_PORT: 6379
    command: celery -A app.celery_config.celery_app worker --loglevel=info
    depends_on:
      - redis
      - db
    networks:
      - my_network
    restart: unless-stopped

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
